### ISSUE TITLE
Metric containing `-` causes "is not a valid metric name" error

### ISSUE THREAD

**Issue by mschirrmeister** [albertito/prometheus-expvar-exporter#1]
Hello,

when I query an **expvars** endpoint, I get the following error.

```
2024/04/14 19:50:51 Collecting "https://192.168.2.199:8443/routedns/vars"
2024/04/14 19:50:51 Listening on ":8000"
panic: "routedns.listener.local-tcp.maxqueue" is not a valid metric name

goroutine 70 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
	/Users/marco/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/value.go:130
main.(*Collector).Collect(0xc0002645d0, 0xc000252e40)
	/Users/marco/MyData/git/public/prometheus-expvar-exporter/main.go:151 +0xab1
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/Users/marco/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:458 +0xe5
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 66
	/Users/marco/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/registry.go:548 +0xbab
```

The full data from the endpoint looks like this.

```
{
"cmdline": ["./routedns","/app/routedns.toml","--log-level","6"],
"memstats": {"Alloc":1668368,"TotalAlloc":1668368,"Sys":11885584,"Lookups":0,"Mallocs":19807,"Frees":1220,"HeapAlloc":1668368,"HeapSys":7667712,"HeapIdle":4907008,"HeapInuse":2760704,"HeapReleased":4775936,"HeapObjects":18587,"StackInuse":720896,"StackSys":720896,"MSpanInuse":64160,"MSpanSys":65280,"MCacheInuse":9600,"MCacheSys":15600,"BuckHashSys":7794,"GCSys":2054128,"OtherSys":1354174,"NextGC":4194304,"LastGC":0,"PauseTotalNs":0,"PauseNs":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"PauseEnd":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"NumGC":0,"NumForcedGC":0,"GCCPUFraction":0,"EnableGC":true,"DebugGC":false,"BySize":[{"Size":0,"Mallocs":0,"Frees":0},{"Size":8,"Mallocs":240,"Frees":0},{"Size":16,"Mallocs":4443,"Frees":0},{"Size":24,"Mallocs":2388,"Frees":0},{"Size":32,"Mallocs":913,"Frees":0},{"Size":48,"Mallocs":5161,"Frees":0},{"Size":64,"Mallocs":631,"Frees":0},{"Size":80,"Mallocs":2160,"Frees":0},{"Size":96,"Mallocs":773,"Frees":0},{"Size":112,"Mallocs":330,"Frees":0},{"Size":128,"Mallocs":466,"Frees":0},{"Size":144,"Mallocs":51,"Frees":0},{"Size":160,"Mallocs":123,"Frees":0},{"Size":176,"Mallocs":98,"Frees":0},{"Size":192,"Mallocs":12,"Frees":0},{"Size":208,"Mallocs":72,"Frees":0},{"Size":224,"Mallocs":14,"Frees":0},{"Size":240,"Mallocs":14,"Frees":0},{"Size":256,"Mallocs":51,"Frees":0},{"Size":288,"Mallocs":210,"Frees":0},{"Size":320,"Mallocs":51,"Frees":0},{"Size":352,"Mallocs":33,"Frees":0},{"Size":384,"Mallocs":2,"Frees":0},{"Size":416,"Mallocs":21,"Frees":0},{"Size":448,"Mallocs":42,"Frees":0},{"Size":480,"Mallocs":1,"Frees":0},{"Size":512,"Mallocs":21,"Frees":0},{"Size":576,"Mallocs":19,"Frees":0},{"Size":640,"Mallocs":10,"Frees":0},{"Size":704,"Mallocs":13,"Frees":0},{"Size":768,"Mallocs":4,"Frees":0},{"Size":896,"Mallocs":46,"Frees":0},{"Size":1024,"Mallocs":12,"Frees":0},{"Size":1152,"Mallocs":30,"Frees":0},{"Size":1280,"Mallocs":4,"Frees":0},{"Size":1408,"Mallocs":7,"Frees":0},{"Size":1536,"Mallocs":7,"Frees":0},{"Size":1792,"Mallocs":11,"Frees":0},{"Size":2048,"Mallocs":15,"Frees":0},{"Size":2304,"Mallocs":21,"Frees":0},{"Size":2688,"Mallocs":2,"Frees":0},{"Size":3072,"Mallocs":3,"Frees":0},{"Size":3200,"Mallocs":0,"Frees":0},{"Size":3456,"Mallocs":1,"Frees":0},{"Size":4096,"Mallocs":26,"Frees":0},{"Size":4864,"Mallocs":10,"Frees":0},{"Size":5376,"Mallocs":6,"Frees":0},{"Size":6144,"Mallocs":7,"Frees":0},{"Size":6528,"Mallocs":0,"Frees":0},{"Size":6784,"Mallocs":0,"Frees":0},{"Size":6912,"Mallocs":0,"Frees":0},{"Size":8192,"Mallocs":1,"Frees":0},{"Size":9472,"Mallocs":9,"Frees":0},{"Size":9728,"Mallocs":0,"Frees":0},{"Size":10240,"Mallocs":0,"Frees":0},{"Size":10880,"Mallocs":0,"Frees":0},{"Size":12288,"Mallocs":0,"Frees":0},{"Size":13568,"Mallocs":0,"Frees":0},{"Size":14336,"Mallocs":0,"Frees":0},{"Size":16384,"Mallocs":0,"Frees":0},{"Size":18432,"Mallocs":1,"Frees":0}]},
"routedns.cache.cache.entries": 0,
"routedns.cache.cache.hit": 0,
"routedns.cache.cache.miss": 0,
"routedns.client.bootstrap-resolver.drop": 0,
"routedns.client.bootstrap-resolver.error": {},
"routedns.client.bootstrap-resolver.maxqueue": 0,
"routedns.client.bootstrap-resolver.query": 0,
"routedns.client.bootstrap-resolver.response": {},
"routedns.client.loopx-roo-doq.drop": 0,
"routedns.client.loopx-roo-doq.error": {},
"routedns.client.loopx-roo-doq.maxqueue": 0,
"routedns.client.loopx-roo-doq.query": 0,
"routedns.client.loopx-roo-doq.response": {},
"routedns.listener.local-tcp.drop": 0,
"routedns.listener.local-tcp.error": {},
"routedns.listener.local-tcp.maxqueue": 0,
"routedns.listener.local-tcp.query": 0,
"routedns.listener.local-tcp.response": {},
"routedns.listener.local-udp.drop": 0,
"routedns.listener.local-udp.error": {},
"routedns.listener.local-udp.maxqueue": 0,
"routedns.listener.local-udp.query": 0,
"routedns.listener.local-udp.response": {}
}
```

Any idea why I get this error? The data itself is ok as far as I know.

**Comment by mschirrmeister** [comment]
I guess it has something to do with the variable naming. If I manually define the `expvar` in the config, the error goes away. But when I define a `label_name` I get another error.

config
```
m.var_a.expvar = "routedns.cache.cache.entries"
m.var_a.help = "routedns cache entries"
m.var_a.label_name = "entries"
```

error
```
2024/04/14 23:54:20 Collecting "https://192.168.2.199:8443/routedns/vars"
2024/04/14 23:54:20 Listening on ":8000"
panic: inconsistent label cardinality: expected 1 label values but got 0 in []string(nil)

goroutine 62 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
	/Users/marco/go/pkg/mod/github.com/prometheus/client_golang@v1.19.0/prometheus/value.go:129
main.(*Collector).Collect(0xc00028d560, 0xc0002e1080)
	/Users/marco/MyData/git/public/prometheus-expvar-exporter/main.go:152 +0xab6
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/Users/marco/go/pkg/mod/github.com/prometheus/client_golang@v1.19.0/prometheus/registry.go:457 +0xe5
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 58
	/Users/marco/go/pkg/mod/github.com/prometheus/client_golang@v1.19.0/prometheus/registry.go:547 +0xbab
```

**Comment by albertito** [comment]
Thanks for the report!

You're correct that the error is due to the `-` and `.` characters, which are unsupported in metric names by Prometheus.

By default, prometheus-expvar-exporter will only automatically replace `/`, but not other characters.

I just pushed a patch c1785e52dd3441ab04db6b26b7967c334521ec9f to the `next` branch to do auto-replacement of all unsupported ASCII characters, and clarifying the error message for the cases of non-ascii characters.

Would you mind giving it a try to see if it solves your problem?

Thank you!

**Comment by albertito** [comment]
> But when I define a `label_name` I get another error.
> 
> config
> 
> ```
> m.var_a.expvar = "routedns.cache.cache.entries"
> m.var_a.help = "routedns cache entries"
> m.var_a.label_name = "entries"
> ```
> 
> error
> 
> ```
> 2024/04/14 23:54:20 Collecting "https://192.168.2.199:8443/routedns/vars"
> 2024/04/14 23:54:20 Listening on ":8000"
> panic: inconsistent label cardinality: expected 1 label values but got 0 in []string(nil)
> ```

This is because that expvar does not have any labels, it is a scalar variable and not a map. And because you're defining a `label_name`, the code expects it to be a map.

If you remove the `label_name` line, it should work.

That said, with the auto-replacement patch from the previous comment you shouldn't need to manually define them (unless the auto-replacement logic isn't doing what you want :).

**Comment by mschirrmeister** [comment]
Works perfectly with the patch. Thank you. 😄 

And yes, I do not use any **label** config. I was not sure what it would exactly do or how it behaves.
